all: acme \
	edwood \
	9term \
	rio

9term:
	sudo cp ./9term.desktop /usr/share/applications/
rio:
	sudo cp ./rio.desktop /usr/share/xsessions/
edwood:
	sudo cp ./edwood.desktop /usr/share/applications/
acme:
	sudo cp ./acme.desktop /usr/share/applications/
	
